service: MLSheet
 
provider:
  name: aws
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      mlsheet-image:
        path: ./
        buildArgs:
          MODEL_PATH: ${env:MODEL_PATH}
          INPUT_COLUMNS: ${env:INPUT_COLUMNS}
          PYTHON_DEPENDENCIES: ${env:PYTHON_DEPENDENCIES, ""}
          SYSTEM_DEPENDENCIES: ${env:SYSTEM_DEPENDENCIES, ""}
        platform: linux/amd64
 
functions:
  mlsheetFunction:
    image:
      name: mlsheet-image
    events:
      - http:
          path: /
          method: post
          cors: true
    timeout: 300